name: Prepare data

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  prepare-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Run Script to Prepare data
      run: node build_scripts/prepare_data.mjs

    - name: Commit and Push Changes
      env:
        GH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Remove spaces from JSON file"
          git push
        else
          echo "No changes to commit."
        fi
